---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: tracing
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.22
          env:
            - name: "COLLECTOR_ZIPKIN_HOST_PORT"
              value: "9412"
          ports:
            - name: "zipkin"
              containerPort: 9412
            - name: "metrics"
              containerPort: 14269
            - name: "jaeger-ui"
              containerPort: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: tracing
spec:
  selector:
    app: jaeger
  type: ClusterIP
  ports:
    - name: "zipkin"
      port: 9412
      targetPort: 9412
    - name: "metrics"
      port: 14269
      targetPort: 14269
    - name: "jaeger-ui"
      port: 16686
      targetPort: 16686
---
