---
# Publish and Subscribe
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis.state-management.svc:6379
    - name: redisPassword
      value: ""
---
# Isolated State Store
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
---
# Shared Blob State Store
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: blob
spec:
  type: state.redis
  version: v1
  metadata:
    - name: keyPrefix
      value: "name"
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "false"
---
# Shared Cache State Store
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cache
spec:
  type: state.redis
  version: v1
  metadata:
    - name: keyPrefix
      value: "name"
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "false"
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://jaeger.tracing.svc:9412/api/v2/spans"
---
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: secretstore
# spec:
#   type: secretstores.local.file
#   version: v1
#   metadata:
#     - name: secretsFile
#       value: /opt/secrets.json
#     - name: nestedSeparator
#       value: ":"
